# Generated by Django 2.1.2 on 2018-10-22 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20181021_1823'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phonenumber',
            unique_together={('contact', 'phone')},
        ),
    ]
