# Generated by Django 2.1.2 on 2018-10-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20181022_0354'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
