# Generated by Django 2.1.2 on 2018-10-22 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_emailfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailfield',
            name='contact',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='contacts.Contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailfield',
            name='email',
            field=models.EmailField(default='', max_length=254, unique=True),
            preserve_default=False,
        ),
    ]
