# Generated by Django 2.1.2 on 2018-10-23 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20181022_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
