# Generated by Django 2.1.2 on 2018-10-23 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_addressfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressfield',
            name='address',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addressfield',
            name='city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addressfield',
            name='contact',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='contacts.Contact'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addressfield',
            name='country',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addressfield',
            name='state',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addressfield',
            name='zip_code',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='addressfield',
            unique_together={('contact', 'address', 'city', 'state', 'country', 'zip_code')},
        ),
    ]
